#if defined _command_included
 #endinput
#endif
#define _command_included

#define COMMAND_ARG_MAX_LENGTH 256

#define COMMAND_USAGE_PREFIX "[SM] Usage: "
#define COMMAND_DESCRIPTION_MOVE_PLAYER "sm_tm_move_player <#userid|name> <type>"
#define COMMAND_DESCRIPTION_SWAP_TEAMS "sm_tm_swap_teams"
#define COMMAND_DESCRIPTION_SCRAMBLE_TEAMS "sm_tm_scramble_teams"
#define COMMAND_DESCRIPTION_BALANCE_TEAMS "sm_tm_balance_teams <type>"
