#if defined _menu_included
 #endinput
#endif
#define _menu_included

#define TEXT_BUFFER_MAX_SIZE 1024
#define MENU_ITEM_INFO_MAX_SIZE 64

#define TEAM_MANAGER "Team manager"
#define MOVE_PLAYER "Move player"
#define IMMEDIATELY "Immediately"
#define AFTER_DEATH "After death"
#define AFTER_ROUND_END "After round end"
#define TO_SPECTATORS "To spectators"
#define SWAP_TEAMS "Swap teams"
#define SCRAMBLE_TEAMS "Scramble teams"
#define BALANCE_TEAMS "Balance teams"
#define MOVE_EXCESS_PLAYERS_TO_SPECTATORS "Move excess players to spectators"
#define DISTRIBUTE_EXCESS_PLAYERS "Distribute excess players"
#define SELECT_PLAYER "Select a player"

#define MENU_PLAYER_ITEM "%N"
#define MENU_PLAYER_ITEM_ENABLED "[x] %N"
#define MENU_PLAYER_ITEM_DISABLED "[_] %N"

#define ADMIN_MENU "adminmenu"
